blog/urls.py
from django.contrib import admin
from django.urls import path


from .views import AboutUsView, CategoryListView, PostDetailView, PostListView, add_post, comment_post, dislike_post, like_post
# dislike_post, like_post

urlpatterns = [
    path('', PostListView.as_view(), name='home'),
    path('', CategoryListView.as_view(), name='categories'),
    path('<int:pk>', PostDetailView.as_view(), name='post_detail'),
    path('create/', add_post, name='create'),
    path('<post_id>/comment', comment_post, name='comment'),
    path('<post_id>/like', like_post, name='like'),
    path('<post_id>/dislike', dislike_post, name='dislike'),
    path('aboutus', AboutUsView.as_view(), name='aboutus'),
    # path('category/<slug:pk>', CategoryListView.as_view()
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('blog/', include('blog.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from account.models import Account
from django.db.models.deletion import CASCADE



class Category(models.Model):

    name = models.CharField(max_length=30, primary_key=True)
    about = models.TextField()
    photo = models.ImageField(upload_to = 'c_image', null = True)
    icon = models.ImageField(upload_to = 'с_icom', null = True)

    def str(self) -> str:
        return f"{self.name}"
        
class Post(models.Model):
    title = models.CharField(max_length=100)
    photo = models.ImageField(upload_to='images/')
    text = models.TextField()
    category = models.ForeignKey(Category, on_delete=CASCADE)
    author = models.ForeignKey(Account, on_delete=CASCADE, default=Account)
    approved_by = models.ManyToManyField(Account, related_name="+++", default=Account)
    created_time = models.DateTimeField(auto_now_add=True)

    
    

class Comment(models.Model):
    author = models.ForeignKey(Account, on_delete=CASCADE)
    text = models.TextField()
    post = models.ForeignKey(Post, on_delete=CASCADE)
    created_time = models.DateField(auto_now_add=True)

class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=CASCADE)
    author = models.ForeignKey(Account, on_delete=CASCADE)
    liked_at = models.DateField(auto_now_add=True)  

    def save(self, *args, **kwargs) -> None:
        self.post.dislike_set.filter(author=self.author).delete()
        return super().save(*args, **kwargs)  

    

class Dislike(models.Model):
    post = models.ForeignKey(Post, on_delete=CASCADE)
    author = models.ForeignKey(Account, on_delete=CASCADE)
    liked_at = models.DateField(auto_now_add=True)  

    def save(self, *args, **kwargs) -> None:
        self.post.like_set.filter(author=self.author).delete()
        return super().save(*args, **kwargs)


    

templates/about.html
{% extends 'base.html' %}




  {% block content %}

  <!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: Arial, Helvetica, sans-serif;
  margin: 0;
}

html {
  box-sizing: border-box;
}

*, *:before, *:after {
  box-sizing: inherit;
}

.column {
  float: left;
  width: 33.3%;
  margin-bottom: 16px;
  padding: 0 8px;
}

.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  margin: 8px;
}

.about-section {
  padding: 50px;
  text-align: center;
  background-color: #474e5d;
  color: white;
}

.container {
  padding: 0 16px;
}

.container::after, .row::after {
  content: "";
  clear: both;
  display: table;
}

.title {
  color: grey;
}

.button {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color: #000;
  text-align: center;
  cursor: pointer;
  width: 100%;
}

.button:hover {
  background-color: #555;
}

@media screen and (max-width: 650px) {
  .column {
    width: 100%;
    display: block;
  }
}
</style>
</head>
<body>

<div class="about-section">
  <h1>About Us</h1>
  <p>Blog to post articles with photos and comments</p>
  
</div>

<h2 style="text-align:center">Our Team</h2>
<div class="row">
  <div class="column">
    <div class="card">
      <img src="/w3images/team1.jpg" alt="" style="width:100%">
      <div class="container">
        <h2>Maksud</h2>
        <p class="title">CEO & Founder</p>
        <p>Some text that describes me lorem ipsum ipsum lorem.</p>
        
        <!-- <p><button class="button">Contact</button></p> -->
      </div>
    </div>
  </div>

  <div class="column">
    <div class="card">
      <img src="/w3images/team2.jpg" alt="" style="width:100%">
      <div class="container">
        <h2>Maksud</h2>
        <p class="title">Art Director</p>
        <p>Some text that describes me lorem ipsum ipsum lorem.</p>
        
        <!-- <p><button class="button">Contact</button></p> -->
      </div>
    </div>
  </div>
  
  <div class="column">
    <div class="card">
      <img src="/w3images/team3.jpg" alt="" style="width:100%">
      <div class="container">
        <h2>Maksud</h2>
        <p class="title">Designer</p>
        <p>Some text that describes me lorem ipsum ipsum lorem.</p>
      
        <!-- <p><button class="button">Contact</button></p> -->
      </div>
    </div>
  </div>
</div>

</body>
</html>
  

  {% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Alex+Brush&family=Praise&display=swap" rel="stylesheet">
  
  <style>
    /* Set height of the grid so .sidenav can be 100% (adjust if needed) */
    .row.content {height: 1500px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      background-color: #f1f1f1;
      height: 100%;
      
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    /* @media screen and (max-width: 767px) { */
      .sidenav {
        height: 2000px;
        padding: 15px;
        background-color: #05386b;
        overflow: hidden;
      }
      .row.content {height: auto;} 
    /* } */
    .navbar {
        background-color:#05386b;
    }
    .username {
        padding-left: 675%;
    }
    /* .author {
        padding-left: 50%;
    } */
    .nav-stacked li {
        list-style: none;
    }
    .nav-stacked li:after {
        content: "\A";
        white-space: pre;
    }
  </style>
</head>

    <body>
        

        
            <div>
                <nav class="navbar navbar-dark navbar-expand-lg navbar-light">
                    <a class="navbar-brand" style="font-family: 'Praise', cursive; font-size: 40px;" href="{% url 'home' %}">Blog</a>
                    

                    
                    
                
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav mr-auto">
                            
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'aboutus' %}">AboutUs</a>
                            </li>
                            {% if not user.is_authenticated %}
                            <li class="nav-item active username">
                                <a class="nav-link" href="{% url 'login' %}">Login</a>
                            </li>
                            
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'register' %}">Register</a>
                            </li>
                            {% elif user.is_authenticated %}
                            <li class="nav-item active username" >
                                <a class="nav-link" href="#"> <i>{{ user.username }}</i>&#160;&#160;|</a>
                            </li>
                            <li class="nav-item active logout" >
                                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                            </li>
                            {% endif %}
                            
                            </li>
                        </ul>
                        
                    </div>
                </nav>
            </div>
            <div class="container-fluid">
                <div class="row content">
                    <div class="col-sm-2 sidenav">
                        <h4 style="color: #f1f1f1;">Select the categories:</h4>
                        <ul class="nav nav-pills nav-stacked">
                            <!-- <li class="active"><a href="#section1">Most liked</a></li> <n></n>
                            <li><a href="#section2">Most viewed</a></li>
                            <li><a href="#section3">Most reacted</a></li>
                            <li><a href="#section3">Photoseververe</a></li> -->
                            
                            {% for c in category_list %}
                            <li><a href="#">{{c.name}}</a></li><br>
                            {% endfor %}
                               
                        </ul><br>
                    </div> 
                
            

                    <div class="col-sm-10 ">
                    
                        {% block content %}
                        {% endblock %}
                        
                        
                    </div>
            </div>    
    

    </body>
</html>